import Calculator from "./calculator/page";
import Clock from "./clock/page";
import MicrosoftEdge from "./microsoft_edge/page";
import MicrosoftStore from "./microsoft_store/page";
import MicrosoftTeams from "./microsoft_teams/page";
import Notepad from "./notepad/page";
import OnscreenKeyboard from "./onscreen_keyboard/page";
import Search from "./search/page";
import Settings from "./settings/page";
import Start from "./start/page";
import TaskManager from "./task_manager/page";
import ToDoList from "./todo_list/page";

export {
  Settings,
  Start,
  MicrosoftStore,
  Search,
  Clock,
  Notepad,
  Calculator,
  TaskManager,
  MicrosoftEdge,
  MicrosoftTeams,
  OnscreenKeyboard,
  ToDoList,
};

//   Edge,
//   Calendar,
//   FileExplorer,
//   Weather,
//   Photos,
//   News,
//   Music,
//   Videos,
//   Games,
//   ControlPanel,
//   Paint,
//   SnippingTool,
//   VoiceRecorder,
//   AlarmClock,
//   StickyNotes,
//   Calculator,
//   Maps,
//   OneDrive,
//   Teams,
//   Skype,
//   PowerPoint,
//   Word,
//   Excel,
//   Access,
//   Publisher,
//   Visio,
//   Project,
//   OneNote,
//   SharePoint,
//   Yammer,
//   Dynamics,
//   Azure,
//   Intune,
//   WindowsSecurity,
//   WindowsDefender,
//   WindowsUpdate,
//   WindowsBackup,
//   WindowsRecovery,
//   WindowsAccessibility,
//   WindowsInk,
//   WindowsHello,
//   WindowsMixedReality,
//   WindowsVirtualDesktop,
//   WindowsSubsystemForLinux,
//   WindowsTerminal,
//   WindowsPowerShell,
//   WindowsCommandPrompt,
//   WindowsFileExplorer,
//   WindowsTaskManager,
//   WindowsSettings,
//   WindowsControlPanel,
//   WindowsEventViewer,
//   WindowsDeviceManager,
//   WindowsDiskManagement,
//   WindowsResourceMonitor,
//   WindowsPerformanceMonitor,
//   WindowsReliabilityMonitor,
//   WindowsTaskScheduler,
//   WindowsSystemConfiguration,
//   WindowsSystemInformation,
//   WindowsSystemProperties,
//   WindowsSystemRestore,
//   WindowsSystemImageBackup,
//   WindowsSystemRepair,
//   WindowsSystemReset,
//   WindowsSystemRefresh,
//   WindowsSystemFileChecker,
//   WindowsSystemDiagnostics,
//   WindowsSystemPerformance,
//   WindowsSystemSecurity,
//   WindowsSystemUpdates,
//   WindowsSystemBackup,
//   WindowsSystemRecovery,
//   WindowsSystemAccessibility,
//   WindowsSystemInk,
//   WindowsSystemHello,
//   WindowsSystemMixedReality,
//   WindowsSystemVirtualDesktop,
//   WindowsSystemSubsystemForLinux,
//   WindowsSystemTerminal,
//   WindowsSystemPowerShell,
//   WindowsSystemCommandPrompt,
//   WindowsSystemFileExplorer,
//   WindowsSystemTaskManager,
//   WindowsSystemSettings,
//   WindowsSystemControlPanel,
//   WindowsSystemEventViewer,
//   WindowsSystemDeviceManager,
//   WindowsSystemDiskManagement,
//   WindowsSystemResourceMonitor,
//   WindowsSystemPerformanceMonitor,
//   WindowsSystemReliabilityMonitor,
//   WindowsSystemTaskScheduler,
//   WindowsSystemConfiguration,
//   WindowsSystemInformation,
//   WindowsSystemProperties,
//   WindowsSystemRestore,
//   WindowsSystemImageBackup,
//   WindowsSystemRepair,
//   WindowsSystemReset,
//   WindowsSystemRefresh,
//   WindowsSystemFileChecker,
//   WindowsSystemDiagnostics,
//   WindowsSystemPerformance,
//   WindowsSystemSecurity,
//   WindowsSystemUpdates,
//   WindowsSystemBackup,
//   WindowsSystemRecovery,
//   WindowsSystemAccessibility,
//   WindowsSystemInk,
//   WindowsSystemHello,
//   WindowsSystemMixedReality,
//   WindowsSystemVirtualDesktop,
//   WindowsSystemSubsystemForLinux,
//   WindowsSystemTerminal,
//   WindowsSystemPowerShell,
//   WindowsSystemCommandPrompt,
//   WindowsSystemFileExplorer,
//   WindowsSystemTaskManager,
//   WindowsSystemSettings,
//   WindowsSystemControlPanel,
//   WindowsSystemEventViewer,
//   WindowsSystemDeviceManager,
//   WindowsSystemDiskManagement,
//   WindowsSystemResourceMonitor,
//   WindowsSystemPerformanceMonitor,
//   WindowsSystemReliabilityMonitor,
//   WindowsSystemTaskScheduler,
//   WindowsSystemConfiguration,
//   Windows,
